services:
  umbrel:
    image: dockurr/umbrel
    container_name: umbrel
    pid: host
    ports:
      - 80:80
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    stop_grace_period: 1m