services:
  umbrel:
    image: dockurr/umbrel
    container_name: umbrel
    pid: host
    ports:
      - 80:80
    volumes:
      - "${DIR_STORAGE}:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped