# see https://chrisgrime.medium.com/deploy-nextcloud-with-docker-compose-935a76a5eb78
# and https://github.com/hackerbande-nbg/decentralize-your-internet/blob/main/infra/nextcloud/compose.yml

---
version: '3'

services:
  nextcloud:
    image: nextcloud:latest
    restart: always
    networks:
      - priv
    depends_on:
      - db
      - redis
    ports:
      - 8092:80
    volumes:
      - ./html:/var/www/html
      - ./custom_apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
    environment:
      - "PYTHONUNBUFFERED=1"
      - PHP_MEMORY_LIMIT=4096M
      - PHP_UPLOAD_LIMIT=102400M # Attention, seems Nextcloud Desktop Client needs logout + login to respect this

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./psql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data
      - "PYTHONUNBUFFERED=1"
    networks:
      - priv

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./redis:/data
    networks:
      - priv

networks:
  priv:
    name: priv
    driver: bridge