# see https://www.reddit.com/r/selfhosted/comments/1755i7o/help_running_this_docker_image_filebrowser/
# docker-compose.yml
services:
  filebrowser:
    image: filebrowser/filebrowser
    user: 1000:1000
    ports:
      - "8080:80"
    volumes:
      - ./data:/srv # files will be stored here
      - ./filebrowser.db:/database.db # users info/settings will be stored here
      - ./filebrowser.json:/.filebrowser.json # config file
    restart: always
